type Mapping=Record<string,string|null>
type DemoRow={id:string;raw_text:string;row_number:number;source_file:string;date_raw:string|null;date_value:string|null;date_error:number;version:string|null;platform:string|null;source:string|null;rating:number|null;sentiment:string;severity:string;theme:string}
type DemoCluster={id:number;name:string;description:string;status:'active'|'hidden'|'merged';members:string[]}
type DemoDataset={id:number;name:string;source:string;status:string;imported_count:number;skipped_count:number;duplicate_count:number}
type DemoSet={dataset:DemoDataset;feedback:DemoRow[];clusters:DemoCluster[];reviews:{operation:string;cluster_id:number;at:string}[]}
type DemoState={nextDatasetId:number;nextClusterId:number;sets:DemoSet[]}
const STORE='folio_virtual_datasets_v1'
const HEADERS=['date','version','platform','source','rating','feedback']
const SAMPLE_ROWS=[
 ['2026-09-01','3.2.1','iOS','示例','','导出视频一直卡在 99%，等了十分钟还没完成。'],
 ['2026-09-02','3.2.1','Android','示例','','完成编辑后无法下载，按钮一直转圈。'],
 ['2026-09-03','3.2.1','iOS','示例','','export is stuck at 99% every time'],
 ['2026-09-04','3.2.1','iOS','示例','','新版本导出失败，重试三次还是不行。'],
 ['2026-09-05','3.2.0','Android','示例','','视频下载速度很慢，希望能看到剩余时间。'],
 ['2026-09-05','3.2.1','iOS','示例','','付款成功但会员没有开通。'],
 ['2026-09-06','3.2.1','Android','示例','','已经扣费了，页面还让我再次订阅。'],
 ['2026-09-07','3.2.0','iOS','示例','','订阅状态更新太慢，不知道支付有没有成功。'],
 ['2026-09-08','3.2.1','Android','示例','','登录验证码一直收不到。'],
 ['2026-09-08','3.2.1','iOS','示例','','换手机后登录，之前保存的内容不见了。'],
 ['2026-09-09','3.2.0','iOS','示例','','验证码延迟了好几分钟才到。'],
 ['2026-09-10','3.2.1','iOS','示例','','新界面更好看了，操作也顺手。'],
 ['2026-09-11','3.2.1','Android','示例','','希望可以批量导出多个项目。'],
 ['2026-09-11','3.2.0','iOS','示例','','请增加深色模式，晚上使用更舒服。'],
 ['2026-09-12','3.2.1','iOS','示例','','搜索历史记录时经常找不到之前的内容。'],
 ['2026-09-12','3.2.0','Android','示例','','客服回复很快，问题处理得不错。'],
]
const SAMPLE_MAPPING:Mapping={text:'feedback',date:'date',version:'version',platform:'platform',source:'source',rating:'rating'}
const THEMES:[string,string[],string][]=[
 ['导出与下载异常',['导出','下载','export','download'],'核心流程'],
 ['支付与订阅状态',['付款','支付','扣费','订阅','会员','payment'],'交易体验'],
 ['登录与数据同步',['登录','验证码','换手机','同步','账号'],'账号体验'],
 ['搜索与内容管理',['搜索','找不到','历史记录'],'内容管理'],
 ['功能建议',['希望','增加','建议','批量','深色模式'],'潜在需求'],
]
function initialState():DemoState{try{const saved=JSON.parse(localStorage.getItem(STORE)||'null');if(saved&&Array.isArray(saved.sets)&&Number.isInteger(saved.nextDatasetId)&&Number.isInteger(saved.nextClusterId))return saved}catch{}return {nextDatasetId:1,nextClusterId:1,sets:[]}}
let state=initialState()
function save(){try{localStorage.setItem(STORE,JSON.stringify(state))}catch{}}
function fail(message:string):never{throw new Error(message)}
function hash8(text:string){let n=2166136261;for(const char of text){n^=char.codePointAt(0)||0;n=Math.imul(n,16777619)}return (n>>>0).toString(16).padStart(8,'0')}
function classify(text:string){const lower=text.toLowerCase();const theme=THEMES.find(([,words])=>words.some(word=>lower.includes(word)))?.[0]||'其他反馈';const sentiment=/卡|失败|无法|不见|收不到|扣费|慢|stuck|error/i.test(text)?'negative':/更好看|顺手|不错/.test(text)?'positive':'neutral';return {theme,sentiment,severity:sentiment==='negative'?'medium':'low'}}
function dateInfo(raw:string){if(!raw)return {date_value:null,date_error:0};if(/^\d{4}-\d{2}-\d{2}$/.test(raw)&&!Number.isNaN(Date.parse(raw))&&new Date(raw+'T00:00:00Z').toISOString().slice(0,10)===raw)return {date_value:raw,date_error:0};return {date_value:null,date_error:1}}
function createDataset(name:string,headers:string[],rows:string[][],mapping:Mapping,source:string){const textColumn=mapping.text;if(!textColumn||!headers.includes(textColumn))fail('请选择有效的反馈内容列');const dataset:DemoDataset={id:state.nextDatasetId++,name,source,status:'ready',imported_count:0,skipped_count:0,duplicate_count:0};const set:DemoSet={dataset,feedback:[],clusters:[],reviews:[]};const seen=new Set<string>();for(let i=0;i<rows.length;i++){const values=Object.fromEntries(headers.map((h,j)=>[h,String(rows[i]?.[j]??'')]));const text=(values[textColumn]||'').trim();if(!text){dataset.skipped_count++;continue}if(seen.has(text)){dataset.duplicate_count++;continue}seen.add(text);const rawDate=mapping.date?(values[mapping.date]||'').trim():'';const date=dateInfo(rawDate);const analysis=classify(text);const id=`F-${dataset.id}-${i+(source==='paste'?1:2)}-${hash8(text)}`;const field=(key:string)=>mapping[key]?(values[mapping[key]!]||'').trim()||null:null;const ratingRaw=field('rating');const rating=ratingRaw!==null&&Number.isFinite(Number(ratingRaw))?Number(ratingRaw):null;const item:DemoRow={id,raw_text:text,row_number:i+(source==='paste'?1:2),source_file:name,date_raw:rawDate||null,...date,version:field('version'),platform:field('platform'),source:field('source'),rating,...analysis};set.feedback.push(item);let cluster=set.clusters.find(c=>c.name===analysis.theme);if(!cluster){cluster={id:state.nextClusterId++,name:analysis.theme,description:THEMES.find(t=>t[0]===analysis.theme)?.[2]||'基于文字规则的演示主题',status:source==='sample'&&analysis.theme==='其他反馈'?'hidden':'active',members:[]};set.clusters.push(cluster)}cluster.members.push(id);dataset.imported_count++}if(!set.feedback.length)dataset.status='empty';state.sets.unshift(set);save();return {dataset_id:dataset.id,status:dataset.status,imported:dataset.imported_count,skipped:dataset.skipped_count,duplicate:dataset.duplicate_count,analysis_errors:[]}}
function getSet(id:number){return state.sets.find(s=>s.dataset.id===id)||fail('演示数据集不存在')}
function members(set:DemoSet,cluster:DemoCluster){const ids=new Set(cluster.members);return set.feedback.filter(f=>ids.has(f.id))}
function issue(set:DemoSet,cluster:DemoCluster){return {id:cluster.id,name:cluster.name,description:cluster.description,status:cluster.status,count:members(set,cluster).length,evidence_ids:cluster.members.slice(0,3)}}
function overview(set:DemoSet){const total=set.feedback.length;const negative=set.feedback.filter(f=>f.sentiment==='negative').length;const issues=set.clusters.filter(c=>c.status==='active').map(c=>issue(set,c)).sort((a,b)=>b.count-a.count||a.id-b.id);return {dataset:set.dataset,total,negative,negative_share:total?Math.round(negative/total*1000)/10:0,dated:set.feedback.filter(f=>f.date_value).length,versions:new Set(set.feedback.map(f=>f.version).filter(Boolean)).size,issues,provider:'mock',model_status:'mock'}}
function detail(set:DemoSet,id:number){const cluster=set.clusters.find(c=>c.id===id)||fail('演示主题不存在');const evidence=members(set,cluster);return {cluster:issue(set,cluster),count:evidence.length,share:set.feedback.length?Math.round(evidence.length/set.feedback.length*1000)/10:0,denominator:set.feedback.length,evidence}}
function answer(set:DemoSet,question:string){const o=overview(set);const q=question.trim();if(!o.total)return '模拟回答：当前演示数据集没有有效反馈，无法给出数量或主题。请载入示例数据。';const matched=set.clusters.find(c=>c.status==='active'&&q.includes(c.name));const cluster=matched||(/提及最多|首要|第一/.test(q)?set.clusters.find(c=>c.id===o.issues[0]?.id):undefined);const prefix='模拟回答（演示数据）：\n';if(cluster){const evidence=members(set,cluster);return prefix+`观察到的数据：「${cluster.name}」有 ${evidence.length} 条，占 ${Math.round(evidence.length/o.total*1000)/10}%（分母 ${o.total} 条）。证据：${evidence.slice(0,3).map(x=>x.id).join('、')||'暂无'}。\n可能的解释：相似表达可能指向同一使用场景，不能仅凭反馈证明根因。\n建议核查：点击反馈 ID 查看原文，再结合日志和用户访谈。`}
 if(/版本|对比/.test(q)){if(o.versions<2)return prefix+'观察到的数据：少于两个有效版本，无法比较版本差异。\n建议核查：补充版本字段。';const counts=new Map<string,DemoRow[]>();for(const f of set.feedback){if(f.version)counts.set(f.version,[...(counts.get(f.version)||[]),f])}return prefix+'观察到的数据：'+[...counts].map(([v,rows])=>`${v} 有 ${rows.length} 条（如 ${rows[0].id}）`).join('；')+'。\n可能的解释：版本差异不能直接说明因果。\n建议核查：比较相同渠道与时间窗口。'}
 if(/趋势|增长|日期|时间/.test(q)){const dated=set.feedback.filter(f=>f.date_value);if(dated.length<2)return prefix+'观察到的数据：缺少足够有效日期，无法计算时间分布或增长趋势。';const first=dated[0],last=dated[dated.length-1];return prefix+`观察到的数据：${dated.length} 条反馈有有效日期，范围 ${first.date_value} 至 ${last.date_value}。例证：${first.id}、${last.id}。\n可能的解释：仅凭此样例不能判断真实增长或根因。\n建议核查：按相同时间窗口和采样口径统计。`}
 if(/负向|情绪/.test(q)){const evidence=set.feedback.filter(f=>f.sentiment==='negative');return prefix+`观察到的数据：按演示文字规则标记负向 ${o.negative} 条，占 ${o.negative_share}%（分母 ${o.total} 条），如 ${evidence.slice(0,2).map(x=>x.id).join('、')}。\n建议核查：人工复核情绪分类和原文。`}
 if(/根因|为什么|原因/.test(q))return prefix+'观察到的数据：当前只有反馈原文，不能证明根因。\n可能的解释：可从高频主题排查相关场景。\n建议核查：结合事件日志、发布记录和访谈。'
 return prefix+'观察到的数据：'+o.issues.slice(0,4).map(x=>`${x.name} ${x.count} 条（如 ${x.evidence_ids[0]}）`).join('；')+`。分母为 ${o.total} 条有效反馈。\n可能的解释：提及最多只代表频次，不等于最高优先级。\n建议核查：点击主题和反馈 ID 核对原文，再结合影响范围与严重程度。`}
export async function demoRequest<T>(url:string,options?:RequestInit):Promise<T>{const method=(options?.method||'GET').toUpperCase();const u=new URL(url,'https://demo.local');let result:unknown;const body=typeof options?.body==='string'?JSON.parse(options.body):{};if(u.pathname==='/datasets'&&method==='GET')result=state.sets.map(s=>s.dataset);else if(u.pathname==='/sample'&&method==='POST')result=createDataset('示例反馈 · 2026-09-01 至 09-12',HEADERS,SAMPLE_ROWS,SAMPLE_MAPPING,'sample');else if(u.pathname==='/preview'&&method==='POST'){const file=(options?.body as FormData)?.get('file');if(!(file instanceof File))fail('请选择文件');if(!/\.(csv|tsv|txt|xlsx|xls)$/i.test(file.name))fail('仅支持 CSV、TSV、Excel 或 TXT 文件');result={name:'演示样例 · '+file.name,headers:HEADERS,rows:SAMPLE_ROWS,preview:SAMPLE_ROWS.slice(0,3),estimated:SAMPLE_ROWS.length,suggested_mapping:SAMPLE_MAPPING}}else if(u.pathname==='/import'&&method==='POST'){const input=body as {name:string;headers:string[];rows:string[][];mapping:Mapping;source:string};result=createDataset(input.name,input.headers,input.rows,input.mapping,input.name.startsWith('演示样例')?'sample':input.source)}else{const match=u.pathname.match(/^\/datasets\/(\d+)(?:\/(.*))?$/);if(!match)fail('演示接口不存在');const set=getSet(Number(match[1]));const tail=match[2]||'';if(tail==='overview'&&method==='GET')result=overview(set);else if(tail==='chat'&&method==='POST'){await new Promise(resolve=>setTimeout(resolve,450));result={mode:'mock',answer:answer(set,(body as {question:string}).question||'')}}else if(tail.startsWith('clusters/')){const parts=tail.split('/');const clusterId=Number(parts[1]);if(parts.length===2&&method==='GET')result=detail(set,clusterId);else if(parts[2]==='review'&&method==='POST'){const input=body as {operation:string;name?:string;target_id?:number};const cluster=set.clusters.find(c=>c.id===clusterId)||fail('主题不存在');if(input.operation==='rename'){if(!input.name?.trim())fail('请输入主题名称');cluster.name=input.name.trim()}else if(input.operation==='remove')cluster.status='hidden';else if(input.operation==='merge'){const target=set.clusters.find(c=>c.id===input.target_id&&c.id!==clusterId)||fail('请选择其他主题');target.members=[...new Set([...target.members,...cluster.members])];cluster.members=[];cluster.status='merged'}else fail('不支持的整理操作');set.reviews.push({operation:input.operation,cluster_id:clusterId,at:new Date().toISOString()});save();result=overview(set)}}else if(tail.startsWith('feedback/')&&method==='GET')result={tool:'get_evidence',evidence:set.feedback.find(f=>f.id===decodeURIComponent(tail.slice(9)))||null};else if(tail==='tools/search_feedback'&&method==='GET'){const query=u.searchParams.get('query')||'';result={tool:'search_feedback',evidence:set.feedback.filter(f=>f.raw_text.includes(query)).slice(0,100)}}}if(result===undefined)fail('演示接口不支持此操作');return result as T}
